apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-project-deploy
  labels:
    app: insurance-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-project
  template:
    metadata:
      labels:
        app: insurance-project
    spec:
      containers:
      - name: insurance-project-container
        image: deepakvarshney5576/insurance-project:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-project-np-service
  labels:
   app: insurance-project
spec:
  selector:
    app: insurance-project

  type: NodePort
  ports:
  - nodePort: 31130  
    port: 8083
    targetPort: 8083
