---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insurance
          image: deepakvarshney5576/insurance-project:1.0
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: insureme
